# this script shows
#
# 1.  functions to preprocess the raw CVR files for the five Portland 2024 
#     rank choice elections
#
# 2.  Functions using the stv() function used in the vote package.  
#
# Not to be confused with the stv() function in the STV package.


#. install the vote package if not already downloaded, and load relevant libraries
install.packages("vote")
library(tidyverse)
library(vote)


#. create a lookup table for the princinct id's used in the CVR files.  The lookup
#. standaridzes the precinct format to handle City of Portland precincts that
#. appear in Washington and Clackamas counties.


precinct_reference <- read_csv("data/Precinct_ID_Reference.csv", show_col_types = FALSE) |> 
                            mutate(id_number = str_trim(id_number), 
                                    precinct = str_trim(precinct)
                                  )


# read_pdx_file() geneates a standaridzed data table from the raw CVR data downloaded
# from Multooman County at https://multco.us/info/turnout-and-statistics-november-2024-general-election
# the function deletes records with a value of "undervote" for all six rankings

read_pdx_file <- function(pdx_csv_file) {
  
    read_csv(pdx_csv_file, show_col_types = FALSE) |> 
      select(recordID = "Record Id", precinct = Precinct, 
           rank_1 = "Rank 1",
           rank_2 = "Rank 2",
           rank_3 = "Rank 3",
           rank_4 = "Rank 4",
           rank_5 = "Rank 5",
           rank_6 = "Rank 6" ) |> 
          
           filter(!if_all(rank_1:rank_6, ~ .x == "undervote"))
           
}

# create preprocessed data tables using read_pdx_files()

mayor_2024 <- read_pdx_file("data/pdx_2024_mayor.csv")
council_d1_2024 <- read_pdx_file("data/pdx_2024_council_d1.csv")
council_d2_2024 <- read_pdx_file("data/pdx_2024_council_d2.csv")
council_d3_2024 <- read_pdx_file("data/pdx_2024_council_d3.csv")
council_d4_2024 <- read_pdx_file("data/pdx_2024_council_d4.csv")


# generate an stv object from the preprocessed data tables
#.compute_stv() uses pivot functions to produce one column per candidate
# eliminates overvotes and undervotes (using NA instead)
# ensures that rankings do not have gaps
# and each candidate is ranked only once

# the tablulation of round by round results appears in a data table generated by the
# vote::summary() function

compute_stv <- function(office_inp, seats_num = 1, quota_const = TRUE) {
 
   office <- office_inp |> 
    pivot_longer(cols = !c(recordID, precinct), 
               names_to = "choice_num", values_to = "choice") |> 
    mutate(choice_num = as.numeric(str_sub(choice_num, -1, -1))) |> 
    filter(choice != "undervote") |> 
    filter(!str_detect(choice, "\n")) |> 
    
    group_by(recordID, precinct, choice) |> 
      slice_min(choice_num, with_ties = FALSE) |> 
    ungroup() |> 
    
    group_by(recordID, precinct) |> 
      mutate(choice_num = rank(choice_num)) |> 
    ungroup()


  office <- office |> 
    pivot_wider(id_cols = c("recordID", "precinct"),
              names_from = choice,
              values_from = choice_num) 

  office  |> 
    select(!c(recordID, precinct)) |> 
    vote::stv(nseats=seats_num, constant.quota = quota_const, quiet=TRUE)

}


Sys.time()
  mayor_stv <- compute_stv(mayor_2024, seats_num = 1, quota_const = FALSE)
Sys.time()  #this took 45 minutes to run on my system, for some reason

summary_mayor_stv <- summary(mayor_stv)

Sys.time()
  d1_stv <- compute_stv(council_d1_2024, seats_num = 3)
Sys.time()

summary_d1_stv <- summary(d1_stv)

Sys.time()
  d2_stv <- compute_stv(council_d2_2024, seats_num = 3)
Sys.time()

summary_d2_stv <- summary(d1_stv)

Sys.time()
  d3_stv <- compute_stv(council_d3_2024, seats_num = 3)
Sys.time()
  
summary_d3_stv <- summary(d1_stv)

Sys.time()
  d4_stv <- compute_stv(council_d4_2024, seats_num = 3)
Sys.time()
  
summary_d4_stv <- summary(d4_stv)




        



         










